# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(750, 500)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("recursos/icono.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("")
        MainWindow.setAnimated(True)
        self.centralWidget = QtWidgets.QWidget(MainWindow)#MainWindow hace referencia al padre del central Widget
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralWidget)
        self.plainTextEdit.setAcceptDrops(False)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.gridLayout.addWidget(self.plainTextEdit, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)#Se establece el Widget central con todos los elementos dentro del MainWindow
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 554, 23))
        self.menuBar.setObjectName("menuBar")
        self.menuArchivo = QtWidgets.QMenu(self.menuBar)
        self.menuArchivo.setObjectName("menuArchivo")
        self.menuEditar = QtWidgets.QMenu(self.menuBar)
        self.menuEditar.setObjectName("menuEditar")
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionAbrir = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("recursos/abrir.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbrir.setIcon(icon1)
        self.actionAbrir.setObjectName("actionAbrir")
        self.actionGuardar = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("recursos/guardar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionGuardar.setIcon(icon2)
        self.actionGuardar.setObjectName("actionGuardar")
        self.actionGuardar_como = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("recursos/guardarComo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionGuardar_como.setIcon(icon3)
        self.actionGuardar_como.setObjectName("actionGuardar_como")
        self.actionSalir = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("recursos/salir.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSalir.setIcon(icon4)
        self.actionSalir.setObjectName("actionSalir")
        self.actionCortar = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("recursos/cortar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCortar.setIcon(icon5)
        self.actionCortar.setObjectName("actionCortar")
        self.actionCopiar = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("recursos/copiar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCopiar.setIcon(icon6)
        self.actionCopiar.setObjectName("actionCopiar")
        self.actionPegar = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("recursos/pegar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPegar.setIcon(icon7)
        self.actionPegar.setObjectName("actionPegar")

        self.actionDeshacer = QtWidgets.QAction(MainWindow)
        self.actionDeshacer.setObjectName("actionDeshacer")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("recursos/deshacer.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDeshacer.setIcon(icon8)

        self.actionRehacer = QtWidgets.QAction(MainWindow)
        self.actionRehacer.setObjectName("actionRehacer")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("recursos/rehacer.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRehacer.setIcon(icon9)

        self.actionAcercaDe = QtWidgets.QAction(MainWindow)
        self.actionAcercaDe.setObjectName("actionAcercaDe")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("recursos/acercaDe.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAcercaDe.setIcon(icon10)

        self.mainToolBar.addAction(self.actionAbrir)
        self.mainToolBar.addSeparator()
        self.mainToolBar.addAction(self.actionGuardar)
        self.mainToolBar.addSeparator()
        self.mainToolBar.addAction(self.actionGuardar_como)
        self.mainToolBar.addSeparator()
        self.mainToolBar.addAction(self.actionCortar)
        self.mainToolBar.addSeparator()
        self.mainToolBar.addAction(self.actionCopiar)
        self.mainToolBar.addSeparator()
        self.mainToolBar.addAction(self.actionPegar)
        self.mainToolBar.addSeparator()
        self.mainToolBar.addAction(self.actionDeshacer)
        self.mainToolBar.addSeparator()
        self.mainToolBar.addAction(self.actionRehacer)
        self.mainToolBar.addSeparator()
        self.mainToolBar.addAction(self.actionSalir)
        self.mainToolBar.addSeparator()
        self.mainToolBar.addSeparator()
        self.mainToolBar.addSeparator()
        self.mainToolBar.addAction(self.actionAcercaDe)
        self.menuArchivo.addAction(self.actionAbrir)
        self.menuArchivo.addAction(self.actionGuardar)
        self.menuArchivo.addAction(self.actionGuardar_como)
        self.menuArchivo.addAction(self.actionAcercaDe)
        self.menuArchivo.addAction(self.actionSalir)
        self.menuEditar.addAction(self.actionCortar)
        self.menuEditar.addAction(self.actionCopiar)
        self.menuEditar.addAction(self.actionPegar)
        self.menuEditar.addAction(self.actionDeshacer)
        self.menuEditar.addAction(self.actionRehacer)
        self.menuBar.addAction(self.menuArchivo.menuAction())
        self.menuBar.addAction(self.menuEditar.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Bloc de notas"))
        self.plainTextEdit.setToolTip(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.menuArchivo.setTitle(_translate("MainWindow", "Archivo"))
        self.menuEditar.setTitle(_translate("MainWindow", "Editar"))
        self.actionAbrir.setText(_translate("MainWindow", "Abrir"))
        self.actionAbrir.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionGuardar.setText(_translate("MainWindow", "Guardar"))
        self.actionGuardar.setShortcut(_translate("MainWindow", "Ctrl+G"))
        self.actionGuardar_como.setText(_translate("MainWindow", "Guardar como..."))
        self.actionGuardar_como.setShortcut(_translate("MainWindow", "Ctrl+D"))
        self.actionSalir.setText(_translate("MainWindow", "Salir"))
        self.actionSalir.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionCortar.setText(_translate("MainWindow", "Cortar"))
        self.actionCortar.setShortcut(_translate("MainWindow", "Ctrl+X"))
        self.actionCopiar.setText(_translate("MainWindow", "Copiar"))
        self.actionCopiar.setShortcut(_translate("MainWindow", "Ctrl+C"))
        self.actionPegar.setText(_translate("MainWindow", "Pegar"))
        self.actionPegar.setShortcut(_translate("MainWindow", "Ctrl+V"))
        self.actionDeshacer.setText(_translate("MainWindow", "Deshacer"))
        self.actionDeshacer.setShortcut(_translate("MainWindow", "Ctrl+U"))
        self.actionRehacer.setText(_translate("MainWindow", "Rehacer"))
        self.actionRehacer.setShortcut(_translate("MainWindow", "Ctrl+R"))
        self.actionAcercaDe.setText(_translate("MainWindow", "Acerca de..."))
        self.actionAcercaDe.setShortcut(_translate("MainWindow", "Ctrl+H"))
